config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'home', to: 'home#index'

  resources :recipes, except: [ :show ]

  resources :shopping_items, only: [ :create, :show, :edit, :update, :destroy ] do
    member do
      post 'toggle_stock'
    end
  end
  get 'search_shopping_items', to: 'shopping_items#search'

  resources :shopping_categories

  resource :scratchpad, only: [:update]

  resources :habit_completions
  resources :habits do
    member do
      post 'toggle_completion'
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/shopping_category.rb
class ShoppingCategory < ApplicationRecord
    has_many :shopping_items

    validates :title, presence: true

    scope :cooking_ingredients, -> { where(id: 1) }

end

app/controllers/shopping_categories_controller.rb
class ShoppingCategoriesController < ApplicationController
  before_action :set_shopping_category, only: %i[ show edit update destroy ]

  # GET /shopping_categories
  def index
    @shopping_categories = ShoppingCategory.all
  end

  # GET /shopping_categories/1
  def show
  end

  # GET /shopping_categories/new
  def new
    @shopping_category = ShoppingCategory.new
  end

  # GET /shopping_categories/1/edit
  def edit
  end

  # POST /shopping_categories
  def create
    @shopping_category = ShoppingCategory.new(shopping_category_params)

    if @shopping_category.save
      redirect_to @shopping_category, notice: "Shopping category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /shopping_categories/1
  def update
    if @shopping_category.update(shopping_category_params)
      redirect_to @shopping_category, notice: "Shopping category was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /shopping_categories/1
  def destroy
    @shopping_category.destroy!
    redirect_to shopping_categories_url, notice: "Shopping category was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_category
      @shopping_category = ShoppingCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shopping_category_params
      params.require(:shopping_category).permit(:title, :color, :notes, :importance)
    end
end

app/helpers/shopping_categories_helper.rb
module ShoppingCategoriesHelper
end

app/views/shopping_categories/_form.html.erb
<%= form_with(model: shopping_category) do |form| %>
  <% if shopping_category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(shopping_category.errors.count, "error") %> prohibited this shopping_category from being saved:</h2>

      <ul>
        <% shopping_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-stone-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :color %>
    <%= form.text_field :color, class: "block shadow rounded-md border border-stone-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="p-2 text-xs bg-stone-100 border border-stone-200 rounded">
    <p>
      Colors to choose from: stone, red, orange, amber, yellow, lime, green, emerald,
      teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose.
    </p>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, class: "block shadow rounded-md border border-stone-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :importance %>
    <%= form.number_field :importance, class: "block shadow rounded-md border border-stone-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= button_tag class: "btn-primary" do %>
      <%= render partial: "svgs/check_circle", locals: { classes: "" } %>
    <% end %>
  </div>

<% end %>

app/views/shopping_categories/_shopping_category.html.erb
<div id="<%= dom_id shopping_category %>" class="mx-auto">

  <div class="flex justify-between space-x-10 items-center">
    <h2 class="my-5 text-xl font-bold">
      <%= link_to shopping_category.title, shopping_category %>
    </h2>

    <span class="p-1 border text-stone-500 text-xl shadow hover:shadow-md rounded-lg
           bg-<%= shopping_category.color %>-100/80 border-<%= shopping_category.color %>-300
           shadow-<%= shopping_category.color %>-100 hover:shadow-<%= shopping_category.color %>-200
    ">
      # <%= shopping_category.importance %>
    </span>

  </div>

  <p class="">
    <strong class="block font-medium mb-1">Color:</strong>
    <%= shopping_category.color %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= shopping_category.notes %>
  </p>

  <% if action_name != "show" %>
    <%= link_to edit_shopping_category_path(shopping_category), class: "btn-secondary inline-block" do %>
      <%= render partial: "svgs/pencil", locals: { classes: "" } %>
    <% end %>
    <hr class="mt-6">
  <% end %>

</div>

app/views/shopping_categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", shopping_category: @shopping_category %>

  <div class="mt-2 flex space-x-2">
    <%= link_to shopping_categories_path, class: "btn-secondary" do %>
      <%= render partial: "svgs/arrow_left_circle", locals: { classes: "" } %>
    <% end %>
    <%= button_to shopping_category_path(@shopping_category), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn-danger" do %>
      <%= render partial: "svgs/trash", locals: { classes: "" } %>
    <% end %>
  </div>

</div>

app/views/shopping_categories/index.html.erb
<div class="w-full">

  <% if notice.present? %>
    <div class="flash_notice" id="notice">
      <%= notice %>
    </div>
  <% end %>

  <%= link_to new_shopping_category_path, class: "my-4 px-3 btn-primary flex justify-between rounded-xl font-medium" do %>
    New Category
    <%= render partial: "svgs/plus_document", locals: { classes: "" } %>
  <% end %>

  <div id="shopping_categories" class="min-w-full">
    <%= render @shopping_categories %>
  </div>
</div>

app/views/shopping_categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-xl">New shopping category</h1>

  <%= render "form", shopping_category: @shopping_category %>

  <div class="mt-2 flex">
  <%= link_to shopping_categories_path, class: " btn-secondary" do %>
      <%= render partial: "svgs/arrow_left_circle", locals: { classes: "" } %>
  <% end %>
  </div>

</div>

app/views/shopping_categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <% if notice.present? %>
      <div class="flash_notice" id="notice">
        <%= notice %>
      </div>
    <% end %>

    <%= render @shopping_category %>
    <div class="flex space-x-2">
      <%= link_to shopping_categories_path, class: "btn-secondary" do %>
          <%= render partial: "svgs/arrow_left_circle", locals: { classes: "" } %>
      <% end %>

      <%= link_to edit_shopping_category_path(@shopping_category), class: "btn-secondary" do %>
          <%= render partial: "svgs/pencil", locals: { classes: "" } %>
      <% end %>

      <%= button_to shopping_category_path(@shopping_category), method: :delete, data: { turbo_confirm: "Are you sure?" },
       class: "btn-danger" do %>
          <%= render partial: "svgs/trash", locals: { classes: "" } %>
       <% end %>
    </div>

  </div>
</div>