config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'home', to: 'home#index'

  resources :recipes, except: [ :show ]

  resources :shopping_items, only: [ :create, :show, :edit, :update, :destroy ] do
    member do
      post 'toggle_stock'
    end
  end
  get 'search_shopping_items', to: 'shopping_items#search'

  resources :shopping_categories

  resource :scratchpad, only: [:update]

  resources :habit_completions
  resources :habits do
    member do
      post 'toggle_completion'
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/shopping_item.rb
class ShoppingItem < ApplicationRecord
  belongs_to :shopping_category
  has_many :recipe_items, dependent: :destroy
  has_many :recipes, through: :recipe_items

  validates :stock, inclusion: [true, false]
  validates :title, presence: true
  validates_uniqueness_of :title

  scope :cooking_ingredients, -> { where(shopping_category_id: 1) }

end

app/controllers/shopping_items_controller.rb
class ShoppingItemsController < ApplicationController
  before_action :set_shopping_item, only: %i[ show edit update destroy ]

  def toggle_stock
    @item = ShoppingItem.find(params[:id])

    @item.stock = !@item.stock
    if @item.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("shopping-item-#{@item.id}",
                partial: "home/shopping_item",
                status: :ok,
                locals: { item: @item })
        end
        format.html { redirect_to home_path }
      end
    end
  end

  def search
    @shopping_items = ShoppingItem.cooking_ingredients.where("title LIKE ?", "%#{params[:q]}%")

    respond_to do |format|
      format.json
      #format.html
    end
  end

  # GET /shopping_items/1
  def show
  end

  # GET /shopping_items/1/edit
  def edit
  end

  # POST /shopping_items
  def create
    @shopping_item = ShoppingItem.new(shopping_item_params)
    category = ShoppingCategory.find(@shopping_item.shopping_category_id)


    respond_to do |format|
      if @shopping_item.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("form-#{category.id}",
                                partial: "home/inline_shopping_form",
                                locals: { item: ShoppingItem.new,
                                          category: category,
                                          hide_form: false }),
            turbo_stream.prepend("shopping-items-#{category.id}",
                                partial: "home/shopping_item",
                                locals: { item: @shopping_item })
          ]

        end
        format.html do
          redirect_to @shopping_item, notice: "Shopping item was successfully created."
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("form-#{category.id}",
                                                    partial: "home/inline_shopping_form",
                                                    locals: { item: @shopping_item,
                                                              category: category,
                                                              hide_form: false })
        end
        format.html do
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /shopping_items/1
  def update
    if @shopping_item.update(shopping_item_params)
      redirect_to @shopping_item, notice: "Shopping item was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /shopping_items/1
  def destroy
    @shopping_item.destroy!
    #redirect_to root_url, notice: "Shopping item was successfully destroyed.", status: :see_other
    redirect_to root_url, status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_item
      @shopping_item = ShoppingItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shopping_item_params
      params.require(:shopping_item).permit(:title, :stock, :shopping_category_id, :notes, :unit)
    end
end

app/helpers/shopping_items_helper.rb
module ShoppingItemsHelper
  def format_unit unit, stock
    case unit
      when 'db'
        number_with_precision(stock, precision: 0)
      else
        if stock == 0
          return number_with_precision(stock, precision: 0)
        end
        number_with_precision(stock, precision: 1)
    end
  end


end

app/views/shopping_items/_form.html.erb
<%= form_with(model: shopping_item) do |form| %>
  <% if shopping_item.errors.any? %>
    <div id="error_explanation" class="flash_danger">
      <h2><%= pluralize(shopping_item.errors.count, "error") %> prohibited this shopping_item from being saved:</h2>

      <ul>
        <% shopping_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-stone-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stock, "Do we have it at home now?" %>
    <%= form.check_box :stock, class: "block shadow rounded-md border border-stone-200 outline-none px-3 py-2 mt-2" %>
  </div>

  <div class="my-5">
    <%= form.label :shopping_category_id %>
    <%= form.text_field :shopping_category_id, class: "block shadow rounded-md border border-stone-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, class: "block shadow rounded-md border border-stone-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="flex">
    <%= button_tag class: "btn-primary" do %>
      <%= render partial: "svgs/check_circle", locals: { classes: "" } %>
    <% end %>
    <%= link_to @shopping_item, class: "ml-2 btn-secondary" do %>
      <%= render partial: "svgs/arrow_left_circle", locals: { classes: "" } %>
    <% end %>
  </div>

<% end %>

app/views/shopping_items/_shopping_item.html.erb
<div class="mt-4" id="<%= dom_id shopping_item %>" class="">

  <h1 class="mb-1 text-2xl font-bold">
    <%= shopping_item.title %>
    is
      <% if shopping_item.stock %>
        <span class="px-1 border border-lime-300 bg-lime-100">
        in stock!
        </span>
      <% else %>
        <span class="px-1 border border-red-300 bg-red-100">
        out of stock!
        </span>
      <% end %>
    </span>
  </h1>

  <h2 class="mb-4 ml-3 text-stone-400 text-xl font-bold">
    <%= shopping_item.shopping_category.title %> [<%= shopping_item.shopping_category.id %>]
  </h2>

  <div class="mb-6 ">
    <% if shopping_item.notes.present? %>
      <h3 class="text-xl font-bold">Notes:</h3>
      <p class="whitespace-pre-line"><%= shopping_item.notes %></p>
    <% else %>
      This item doesn't have notes yet!
    <% end %>
  </div>

</div>

app/views/shopping_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", shopping_item: @shopping_item %>
</div>

app/views/shopping_items/show.html.erb
<div class="mx-auto w-full flex">
  <div class="w-full">

    <% if notice.present? %>
      <div class="flash_notice" id="notice">
        <%= notice %>
      </div>
    <% end %>

    <%= render @shopping_item %>

    <hr class="mb-2">
    <div class="flex">
      <%= link_to home_path, class: "btn-secondary" do %>
        <%= render partial: "svgs/arrow_left_circle", locals: { classes: "" } %>
      <% end %>

      <%= link_to edit_shopping_item_path(@shopping_item), class: "ml-2 btn-secondary" do %>
        <%= render partial: "svgs/pencil", locals: { classes: "" } %>
      <% end %>

      <%= button_to shopping_item_path(@shopping_item), method: :delete, data: { turbo_confirm: "Are you sure?" },
      class: "ml-2 btn-danger" do %>
        <%= render partial: "svgs/trash", locals: { classes: "" } %>
      <% end %>
    </div>
    
  </div>

</div>