config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'home', to: 'home#index'

  resources :recipes, except: [ :show ]

  resources :shopping_items, only: [ :create, :show, :edit, :update, :destroy ] do
    member do
      post 'toggle_stock'
    end
  end
  get 'search_shopping_items', to: 'shopping_items#search'

  resources :shopping_categories

  resource :scratchpad, only: [:update]

  resources :habit_completions
  resources :habits do
    member do
      post 'toggle_completion'
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/habit.rb
class Habit < ApplicationRecord
  has_many :habit_completions
end

app/models/habit_completion.rb
class HabitCompletion < ApplicationRecord
  belongs_to :habit
end

app/models/passcode.rb
class Passcode < ApplicationRecord
    has_secure_password
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :recipe_items, dependent: :destroy
    has_many :shopping_items, through: :recipe_items

    validates :title, presence: true
    validates_uniqueness_of :title
    validates :description, presence: true

    def is_everything_in_stock?
        self.shopping_items.all?(&:stock)
    end

end

app/models/recipe_item.rb
class RecipeItem < ApplicationRecord
  belongs_to :recipe
  belongs_to :shopping_item
end

app/models/scratchpad.rb
class Scratchpad < ApplicationRecord
end

app/models/shopping_category.rb
class ShoppingCategory < ApplicationRecord
    has_many :shopping_items

    validates :title, presence: true

    scope :cooking_ingredients, -> { where(id: 1) }

end

app/models/shopping_item.rb
class ShoppingItem < ApplicationRecord
  belongs_to :shopping_category
  has_many :recipe_items, dependent: :destroy
  has_many :recipes, through: :recipe_items

  validates :stock, inclusion: [true, false]
  validates :title, presence: true
  validates_uniqueness_of :title

  scope :cooking_ingredients, -> { where(shopping_category_id: 1) }

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @shopping_categories = ShoppingCategory.includes(:shopping_items)
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: %i[ edit update destroy ]

  def toggle_completion
    @habit = Habit.find(params[:id])
    date = JSON.parse(request.body.read)["date"]

    today_completion = @habit.habit_completions.where(date: date)[0]

    if today_completion
      today_completion.destroy!
      respond_to do |format|
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "habit_completions_#{params[:id]}",
            partial: 'habits/habit_completions',
            locals: { habit: @habit, dates: past_31_days }
          )
        }
        format.html { redirect_to habits_path, notice: "Occurence successfully removed." }
      end
    else
      HabitCompletion.create(habit_id: @habit.id, date: date)
      respond_to do |format|
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "habit_completions_#{params[:id]}",
            partial: 'habits/habit_completions',
            locals: { habit: @habit, dates: past_31_days }
          )
        }
        format.html { redirect_to habits_path, notice: "Occurence added." }
      end
    end
  end

  def past_31_days
    dates = []
    (31.days.ago.to_date..Date.today).each { |date| dates << date }
    dates
  end

  # GET /habits
  def index
    @habits = Habit.all
    @dates = past_31_days
  end

  # GET /habits/new
  def new
    @habit = Habit.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits
  def create
    @habit = Habit.new(habit_params)

    if @habit.save
      redirect_to habits_path, notice: "Habit was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /habits/1
  def update
    if @habit.update(habit_params)
      redirect_to habits_path, notice: "Habit was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

   # DELETE /habits/1
   def destroy
    @habit.destroy!
    redirect_to habits_url, notice: "Habit was successfully destroyed.", status: :see_other
  end

  private
    def habit_params
      params.require(:habit).permit(:name)
    end
    def set_habit
      @habit = Habit.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @shopping_categories = ShoppingCategory.includes(:shopping_items)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: "Recipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to recipes_path, notice: "Recipe was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy!
    redirect_to recipes_url, notice: "Recipe was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, shopping_item_ids: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in_user, only: [:new, :create]

  def new
  end

  def create
    passcode = Passcode.first
    if passcode && passcode.authenticate(params[:password])
      session[:passcode_id] = passcode.id
      redirect_to home_path
    else
      flash.now[:danger] = 'Invalid passcode'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session.delete(:passcode_id)
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_with_hl(link_title, path, classes="font-bold")
    link_to link_title, path, class: (classes if current_page?(path))
  end
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shopping_items_helper.rb
module ShoppingItemsHelper
  def format_unit unit, stock
    case unit
      when 'db'
        number_with_precision(stock, precision: 0)
      else
        if stock == 0
          return number_with_precision(stock, precision: 0)
        end
        number_with_precision(stock, precision: 1)
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yuva</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'long-press-event' %>
  </head>

  <%# <body class="bg-gradient-to-b from-stone-50 to-lime-100/60 min-h-screen"> %>
<body>
    <div class="px-2 mt-4 max-w-[600px] mx-auto">
      <header class="flex justify-between items-center">
        <div class="space-x-2 sm:space-x-6 text-sm">
          <%= link_to_with_hl "Home", home_path %>
          <%= link_to_with_hl "Habits", habits_path %>
          <%= link_to_with_hl "Recipes", recipes_path %>
          <%= link_to_with_hl "Categories", shopping_categories_path %>
        </div>
        <% if session[:passcode_id] %>
          <%= button_to 'Logout', logout_path, method: :delete, class: "text-sm" %>
        <% end %>

      </header>

      <main class="mt-4 flex">
        <%= yield %>
      </main>

    </div>
  </body>
</html>

app/views/svgs/_arrow_left_circle.html.erb
<%# Source: https://heroicons.com/ %>
<svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    class="w-6 h-6 <%= classes %>"
>
    <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M11.25 9l-3 3m0 0l3 3m-3-3h7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
    />
</svg>

app/views/svgs/_check_circle.html.erb
<%# Source: https://heroicons.com/ %>
<svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    class="w-6 h-6 <%= classes %>"
>
  <path
    stroke-linecap="round"
    stroke-linejoin="round"
    d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
    />
</svg>

app/views/svgs/_pencil.html.erb
<%# Source: https://heroicons.com/ %>
<svg 
    xmlns="http://www.w3.org/2000/svg"
    fill="none" viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    class="w-6 h-6 <%= classes %>"
>
    <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125"
    />
</svg>

app/views/svgs/_plus.html.erb
<%# Source: https://heroicons.com/ %>
<svg 
    xmlns="http://www.w3.org/2000/svg" 
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    class="w-6 h-6 <%= classes %>"
>
    <path 
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M12 4.5v15m7.5-7.5h-15"
    />
</svg>

app/views/svgs/_plus_circle.html.erb
<%# Source: https://heroicons.com/ %>
<svg 
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    class="w-6 h-6 <%= classes %>"
>
    <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
    />
</svg>

app/views/svgs/_plus_document.html.erb
<%# Source: https://heroicons.com/ %>
<svg 
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    class="w-6 h-6 <%= classes %>"
>
    <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m3.75 9v6m3-3H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"
    />
</svg>

app/views/svgs/_trash.html.erb
<%# Source: https://heroicons.com/ %>
<svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    class="w-6 h-6 <%= classes %>"
>
    <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
    />
</svg>